FROM ubuntu:24.04

WORKDIR /app

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt install -y ffmpeg vim wget curl sudo gpg git build-essential && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*

RUN apt update; apt-get install -y software-properties-common; add-apt-repository -y ppa:kobuk-team/intel-graphics; apt-get install -y libze-intel-gpu1 libze1 intel-metrics-discovery intel-opencl-icd clinfo intel-gsc; apt-get install -y intel-media-va-driver-non-free libmfx-gen1 libvpl2 libvpl-tools libva-glx2 va-driver-all vainfo; rm -rf /var/lib/apt/lists/*;rm -rf /tmp/*
RUN apt update; apt-get install -y libze-dev intel-ocloc && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*

RUN miniforge_script=Miniforge3-$(uname)-$(uname -m).sh && [ -e $miniforge_script ]; rm $miniforge_script; wget "https://github.com/conda-forge/miniforge/releases/latest/download/$miniforge_script"; bash $miniforge_script -b -u; CONDA_DIR=$HOME/miniforge3; eval "$(${CONDA_DIR}/bin/conda shell.bash hook 2> /dev/null)"; conda init; conda create -n nemotron-s2s python=3.12 -y; conda activate nemotron-s2s; pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/xpu; pip install uvicorn fastapi loguru websockets

RUN CONDA_DIR=$HOME/miniforge3; eval "$(${CONDA_DIR}/bin/conda shell.bash hook 2> /dev/null)"; conda activate nemotron-s2s; git clone https://github.com/NVIDIA-NeMo/NeMo.git; cd NeMo; git checkout 644201898480ec8c8d0a637f0c773825509ac4dc; pip install --no-cache -e ".[asr,tts,rtvi,all]"; pip install "pipecat-ai[silero,openai,cartesia,runner,daily,local-smart-turn-v3,webrtc]==0.0.98"; pip install dotenv websockets aiortc opencv-python



